name 'devops-exercise'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures devops-exercise'
long_description 'Installs/Configures devops-exercise'
version '0.1.0'
